# Generated by Django 5.0.6 on 2024-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(choices=[('ONE-WAY', 'One Way'), ('ROUND-TRIP', 'Round Trip')], max_length=50)),
                ('departure_date', models.CharField(max_length=50)),
                ('return_date', models.CharField(max_length=50)),
                ('passengers', models.CharField(max_length=10)),
            ],
        ),
    ]
