# Generated by Django 5.0.6 on 2024-06-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('International_Flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InternalFlight',
            new_name='InternationalFlight',
        ),
    ]
